### ISSUE TITLE
Créer vos compte github, faire la demande de rejoindre la team vc

### ISSUE THREAD

**Issue by pascalfares** [projets2017cl/vc#1]
Créer vos compte github, faire la demande de rejoindre la team https://github.com/orgs/projets2017cl/teams/vc/members, en reply a cet "issue" dire que vous avex fait la demande de rejoindre la team

**Comment by eliasgkh** [comment]
J'ai fait la demande de rejoindre le team

**Comment by pascalfares** [comment]
@eliasgkh @AlessHo done

**Comment by 0xdecapitator** [comment]
J'ai fais la demande de rejoindre le team

**Comment by AliRifaii** [comment]
@pascalfares : J'ai fais la demande de rejoindre le team

**Comment by firass-semaan** [comment]
j'ai deja fais la demande de rejoindre le team VC

**Comment by MikeRmaily** [comment]
J'ai fait la demande de rejoindre le team

**Comment by jad-gerges** [comment]
J'ai fait la demande de rejoindre le team

**Comment by joseph743** [comment]
J'ai fait la demande de rejoindre le team

**Comment by abdelmajidnadar** [comment]
J'ai fait le demande de rejoindre le team

**Comment by mfaour** [comment]
J'ai fait la demande de rejoindre le team

**Comment by Cynthia-aboumaroun** [comment]
J'ai fait la demande de rejoindre le team

**Comment by isae-edgardchamoun** [comment]
Bonjour Dr Pascal, je n'ai pas pu rejoindre le team car le lien de reference n'existe plus.
![capture3](https://user-images.githubusercontent.com/26340463/27767554-9c36d318-5f03-11e7-9816-907f0d420144.PNG)

**Comment by isae-edgardchamoun** [comment]
J'ai fait la demande de rejoindre le team

**Comment by chreifa** [comment]
J'ai fait la demande

**Comment by t-g-tannous** [comment]
J'ai fait la demande

**Comment by elie-chaaban** [comment]
J'ai fait la demande de rejoindre le team

**Comment by elieohanian** [comment]
J'ai fait la demande de rejoindre le team

**Comment by RidaAli** [comment]
J'ai fait la demande de rejoindre le team

**Comment by ziadbassila** [comment]
Hello Dr.Fares 
i m getting an error "404 page not found" when i click "https://github.com/orgs/projets2017cl/teams/vc/members,"
i already have Github account
what do i have to do?
best regards bassila ziad

**Comment by pascalfares** [comment]
@ziadbassila as tu vérifié ton email? quand tu crées ton compte il faut aussi vérifié l'email que tu as mis.

résssayer aussi https://github.com/orgs/projets2017cl/teams/vc/members a nouveau

**Comment by pascalfares** [comment]
@RidaAli can you help @ziadbassila  and explain to him how you do it?

**Comment by jad-gerges** [comment]
Bonjour Dr.Fares
je suis un etudiant de SMB est ce que je peut faire de plus de développement mobile.

**Comment by joseph743** [comment]
Dear Dr.
My email is verified and i'm still unable to reach the link "https://github.com/orgs/projets2017cl/teams/vc/members" , shouldn't i receive an invitation to join the team from you ?
Regards

**Comment by t-g-tannous** [comment]
Bonjour Dr Pascal ,

J'ai la meme erreur quand je click sur le lien 
![404_git](https://user-images.githubusercontent.com/22727196/27799407-bbfd4496-601d-11e7-96b9-b6dcad2d4fa4.png)

Et voici mon mail

![email_verified](https://user-images.githubusercontent.com/22727196/27799383-9c1dacba-601d-11e7-8d2b-bb2386812e99.png)

Merci

**Comment by t-g-tannous** [comment]
Bonjour Dr Pascal ,

J'ai contacté le support de Github et voici leur réponse concernant l'erreur

![github_support](https://user-images.githubusercontent.com/22727196/27818936-9dec30a6-60a0-11e7-8c20-689919a5c22c.png)

Merci

**Comment by pascalfares** [comment]
@t-g-tannous  https://github.com/orgs/projets2017cl/teams/vc/members

Pour ce type de requêtes faire une nouvelle issue

**Comment by pascalfares** [comment]
Il est probable que vous deviez valide votre email avant d' avoir le droit de demander a joindre une team.

sinon je vous est invité, vous pouvez normalement accepter l'invitation @t-g-tannous @joseph743

**Comment by t-g-tannous** [comment]
@pascalfares  Ok merci ca marche, je suis un membre  👍

**Comment by joseph743** [comment]
@pascalfares Ça marche, merci pour votre aide.

**Comment by Alhajj-Chantale** [comment]
J'ai fait la demande de rejoindre le team

**Comment by Cynthia-aboumaroun** [comment]
Salut Dr. Pascal,


J'essaie toujours rejoindre le groupe des  2 teams (VC et nfp103) mais le
petit chat de github me sumonte.

https://github.com/orgs/projets2017cl/teams/vc/members

quoi faire???

2017-07-05 11:57 GMT+03:00 Alhajj-Chantale <notifications@github.com>:

**Comment by ayounes3333** [comment]
J'ai fait la demande de rejoindre le team

**Comment by ayounes3333** [comment]
J'ai fait la demande de rejoindre le team

**Comment by ansari007** [comment]
404 error :S pouvez vous m'envoyer une invitation @pascalfares ?

**Comment by pascalfares** [comment]
@ansari007 https://github.com/orgs/projets2017cl/teams/vc/members

**Comment by ansari007** [comment]
@pascalfares meme erreur :S

![404](https://user-images.githubusercontent.com/11501271/27909950-b258698a-625b-11e7-931b-e29e641fcdb0.JPG)

**Comment by abbaskarake** [comment]
J'ai fait la demande

**Comment by ansari007** [comment]
@abbaskarake  il ma donne toujours 404 quand je click sur le lien

**Comment by ansari007** [comment]
ok ca marche maintenant merci @pascalfares

**Comment by khattarramy** [comment]
J'ai la même erreur que ansari007 , quand j'essai d'ouvir :   https://github.com/orgs/projets2017cl/teams/vc/members

**Comment by ansari007** [comment]
@khattarramy assure-toi que @pascalfares a t'invitee.

Vérifiez votre notification ou consultez votre Page d'accueil  en Github pour accepter l'invitation :)

**Comment by khattarramy** [comment]
@ansari007 Merci, j'ai pas eu aucune invitation encore.
@pascalfares s'il vous plais, pouvez vous m'envoyer une invitation. sur : https://github.com/orgs/projets2017cl/teams/vc/members

Merci

**Comment by 0xdecapitator** [comment]
Bonjour docteur j'ais toujours une erreur 404. Tu peux m'inviter encore une fois.merci

**Comment by 0xdecapitator** [comment]
@pascalfares
