### ISSUE TITLE
Details sur le projet

### ISSUE THREAD

**Issue by MireilleKhalifeh** [projets2017cl/vc#22]
Pouvez-vous nous fournir plus de détails sur chaque idée.
Merci.

**Comment by pascalfares** [comment]
j'avais donné des idée aussi durant les cours, mais vous êtes libre aussi de proposer vos propre complément pour chaque idée

voici un peu plus de detail http://libresoftware.cofares.net/projets-par-l-open-source-lebanese-movement/gstockr

et plus généralement sur dáutres idées aussi http://libresoftware.cofares.net/projets-par-l-open-source-lebanese-movement

**Comment by MireilleKhalifeh** [comment]
Ok merci je veux le partager sur classroom pour que tout le monde puisse le voir et decider

**Comment by AlessHo** [comment]
Bonjour dr @pascalfares ,

J'ai quelques questions concernant le projet:
1- Il ya une grande lacune concernant le nombre de personnes pour realiser ce projet : Est ce que le projet peut être réalisé en groupe de 4 personnes? Ou bien tous les éleves de smb forment le même groupe pour réaliser le même projet?
2- Comment peut-on vous informer concernant le groupe formé et le projet qu'on a choisi?
3- Je sais qu'on a 120h pour achever le travail. Mais je ne comprend pas comment seront-elles divisées? (ex: 120h de travail peuvent etre 2 mois ou 2 semaines de travail...)
4- Quand on va commencer le projet (directement apres de vous informer) ?

Merci
