### ISSUE TITLE
Questions concernant le projet

### ISSUE THREAD

**Issue by alesshosry** [projets2017cl/vc#25]
Bonjour dr @pascalfares ,

J'ai quelques questions concernant le projet:
1- Il ya une grande lacune concernant le nombre de personnes pour realiser ce projet : Est ce que le projet peut être réalisé en groupe de 4 personnes? Ou bien tous les éleves de smb forment le même groupe pour réaliser le même projet?
2- Comment peut-on vous informer concernant le groupe formé et le projet qu'on a choisi?
3- Je sais qu'on a 120h pour achever le travail. Mais je ne comprend pas comment seront-elles divisées? (ex: 120h de travail peuvent etre 2 mois ou 2 semaines de travail...)
4- Quand on va commencer le projet (directement apres de vous informer) ?

Merci

**Comment by pascalfares** [comment]
1. Le projet a déjà commencer, Et vous êtes en train d'être évalué.
2. 120h est une quantité de travail pas un délai. Si vous travailler 24h par semaines et que je valide ou accepté le travail réalisé vous pourrez terminer en 5 semaines. Mais certain travaillerons plus au début et d'autre plus à la fin. Toit dépend d du genre d'activité que vois faite.
3. tout ce fait ici dans les issues.. ce  que vous faite ou souhaitez faire ou demandes ou questions. Les groupes peuvent être dynamique: Pour tâche A personne "p1 p2 p3" Et pour tâche B "p1 p5"

@projets2017cl/vc
