### ISSUE TITLE
Projet C2

### ISSUE THREAD

**Issue by ChirazeHaidar** [projets2017cl/vc#26]
Bonjour Dr. Pascal
On voulait vous voir pour vous parler à propos du projet C2

On a plein de questions à vous demander, pour pouvoir demarrer le travail.
Le temps passe et on a besoin de bien comprendre ce que vous voulez en details.

Si c'est possible, on souhaite vous voir selon une date precisée par vous.

Merci, cordialement

**Comment by pascalfares** [comment]
N'est -Il pas possible de poser les questions par écrit? Dans les issues ici par exemple....

**Comment by pascalfares** [comment]
Ce que je souhaite (j ai le rôle du client) que vous réaliser un logiciel. Par exemple un logiciel de gestions de bien et de suivi des bien. Vois pouvez proposer un autre! .... 

Une idée de produit --- développement ---» produit

**Comment by pascalfares** [comment]
Utiliser ce processus (par exemple) "Processus Unifié Arrington"

https://drive.google.com/drive/u/1/folders/0B2NK97qOKj2jNXB1VDN5STBNM00
