### ISSUE TITLE
Clarification a propos du projet

### ISSUE THREAD

**Issue by mfaour** [projets2017cl/vc#27]
Bonjour M. Pascal,
Quelle est la prochaine étape, devons-nous commencer à planifier, allouer les ressources et assigner les tâches nous-mêmes,  ou nous devons attendre de vous les instructions?
Merci,

**Comment by pascalfares** [comment]
Je suis le client , Je veux un produit.... C'est à vous de me proposer ce que vois aller faire et comment faire? 

Pas des question abstraite , Mais poser des question précises

**Comment by pascalfares** [comment]
Vous pouvez commencer aussi en disant ou proposant ou demander de l'aide ... (dans les issues ici)

1. Ceci doit être fait
2. J'ai une question
3. besoin d'aide pour xyz
@projets2017cl/vc 

Un bon départ  Suivre ce que je vous est appris "Processus Unifié Arrington" :

https://drive.google.com/drive/u/1/folders/0B2NK97qOKj2jNXB1VDN5STBNM00
