### ISSUE TITLE
Questions a propos du Projet VC

### ISSUE THREAD

**Issue by firass-semaan** [projets2017cl/vc#28]
Bonjour Mr. Pascal,

1. Est-ce qu’il faut choisir une seule idée pour notre projet ou bien on aura deux groupes pour les deux idées? 
2. Peut-on commencer choisir un team-leader et distribuer les taches, ou on va attendre vos instructions ?

Merci infiniment

**Comment by pascalfares** [comment]
@projets2017cl/vc 

Regroupez vous en groupe, avec un leader si possible dans chaque groupe.

Chaque groupe travaillera sur un projet (ou sous partie d' un projet) relativement independant

Par exemple pour la gestion des "biens" stock

Il peut y avoir plusieurs sous-groupe (et sous-sous groupe etc..) chaque groupe d'au plus 5 membres, tous les 2 3 groupes un groupe de 1 ou 2 personnes pour intégration et developper ce qui manque pour mettre ensemble etc... 

1. gestion achat (ou acquisition)
  a. gestion ihm des achat
  b. modèle et metier des achat
  c. etc..
2. gestion des transaction de déplacement de bien entre sites
3. tracking gps des biens
4. gestion des ventes ou session ou prêts
5. etc..

Un groupe ou moi s'occuperont de l'intégration.

un

**Comment by pascalfares** [comment]
. Chaque fois que vous souhaiter que quelque chose soit réalisé (y compris par vous même) l’écrire dans une issue. puis répondre a la demande ("assignees")

**Comment by MireilleKhalifeh** [comment]
"Chaque groupe travaillera sur un projet (ou sous partie d' un projet) relativement independant"
Est ce que cela veut dire qu'on peut travailler sur 2 projets differents et chaque personne decidera sur quel projet il veut travailler? ou tout le monde sur un seul projet??
