### ISSUE TITLE
groupe whatsup glg204 et smb215

### ISSUE THREAD

**Issue by pascalfares** [projets2017cl/vc#29]
besoin de créer les groupes whatsup smb215 et glg204

voici la listes des auditeurs et leurs numéros....

1. https://github.com/projets2017cl/vc/blob/master/glg204.md
2. https://github.com/projets2017cl/vc/blob/master/smb215.md

La tecahe sra affécté au premier qui souhaite le faire...

@projets2017cl/vc

**Comment by ChirazeHaidar** [comment]
Je vais creer le groupe glg204

**Comment by ChirazeHaidar** [comment]
Le group glg204 est bien créé

**Comment by elieohanian** [comment]
Le group smb215 est bien créé

**Comment by pascalfares** [comment]
Je suis membre de ces groupes whatsup?

+9613240246 m' ajouter si ce n' est pas le cas...

M' ajouter en tant qu' administrateur...

**Comment by ChirazeHaidar** [comment]
Done

**Comment by elieohanian** [comment]
ok added
