### ISSUE TITLE
Valeur C

### ISSUE THREAD

**Issue by elieohanian** [projets2017cl/vc#30]
Bonjour Dr.

ce que vous voulez qu'on choisit un projet et faire ces differents taches 
on peut choisir n'import quelle interface  pour travailler ?

Elie Ohanian

**Comment by pascalfares** [comment]
@projets2017cl/vc 

Vous choisisser un produit à réliser (ceux que j'ai proposer ou d'autres)

puis vous déclaré le projet et commencer le processus de développement 

1. Créer le github du projet
2. Fair la liste backlog produit ou USE case
3. distribuer les tâches
4. réaliser les tâches
5. tester
6. Livrer

voici le processus

https://drive.google.com/drive/u/1/folders/0B2NK97qOKj2jNXB1VDN5STBNM00
....

**Comment by elieohanian** [comment]
je peux travailler sur APEX comme interface avec Oracle 12 C database?

**Comment by pascalfares** [comment]
C' est une question prematuré.. Pour quel produit? 

Tu vas rélisé quel poduit? nous verrons comment le deployé et le réalisé dans une étape suivante

... Definir le produit = ensembre d'acteurs qui réalisent des tratements
... Definir l'environnement technique = choisir une architecture tenant compte des possibilités et du besoin (cloud, hebergement, data center, multi sites, licences, client léger ou lourd, etc..)

FAIRE UN PROJET POUR LE CYCLE C CE N"EST PAS UTILISER UN PRODUIT QUE VOUS CONNAISSEZ, MAIS APRRENDRE LE CONTENE DU COURS:

> Réaliser un projet de bout en bout (partir du besoin du client et fournir une solution qui marche en respectant les contraintes)
> Technologie java
> NoSQL
> Cloud 
> Virtualisation
> Mobilité Android 


pour demarrer vous devez me proposer quelque chose de concret par exemple

* gestion de stock multi-site
* gestion d'une entreprise de taxxi style UBER
* gestion d'un outils de workflow générique
* etc ..

Les solutions technique et outils c'est l'étape suivante. On ne commence pas par le clou et le marteau mais par la chaise ou la table!

@projets2017cl/vc

**Comment by elieohanian** [comment]
si on va choisir : * gestion de stock multi-site
-creer client avec des informations relies
-creer item avec des informations relies
- entree sur stock
- transfer entre les different sites
- faire des factures dans les different sites
etc...
