### ISSUE TITLE
Clone Video

### ISSUE THREAD

**Issue by joseph743** [projets2017cl/vc#42]
Dr. Pascal,
Pouvez-vous partager avec nous la video sur la facon de cloner le projet sur github?
Merci

**Comment by pascalfares** [comment]
Je vais en faire une ...  (quand il y aura du calme autour de moi .. pour le son ;)

**Comment by ansari007** [comment]
@joseph743 Salut,tu peux forker le projet 
![fork](https://user-images.githubusercontent.com/11501271/27944444-96810a84-62ef-11e7-9a1b-ee4f41f169a8.JPG)
Maintenant tu vas trouver le projet dans votre projets puis tu peux le cloner en cliquant sur Clone (bouton de couleur vert ) et voila 

@pascalfares

**Comment by pascalfares** [comment]
N'oublier pas d'installer git for windows si vous utiliser windows...

https://git-for-windows.github.io/

**Comment by pascalfares** [comment]
Après install vous aurez un Git Bash: (commande linux dans windows!)

![gitbash](https://user-images.githubusercontent.com/1664478/27945612-6ee992be-62f6-11e7-8683-44a2cde52cde.png)

Faire le Fork du projet 

![fork](https://user-images.githubusercontent.com/1664478/27945866-9495f3ee-62f7-11e7-940c-8e5f258c86de.jpg)

Vous aurez alors une copie exacte du projet actuel chez vous cette foie ci
![forking_li](https://user-images.githubusercontent.com/1664478/27946295-b9c096cc-62f9-11e7-9949-569f5848c723.jpg)
