### ISSUE TITLE
System Informatique pour une entreprise 

### ISSUE THREAD

**Issue by elieohanian** [projets2017cl/vc#46]
Mon idée est de créer un système informatique pour une entreprise qui vente des vêtements
(Comme Aishti, Springfield ....).
1- creer les differents produit(vêtements) (descption,Couleur,size,model,saison) cette partie est cree une seule pour tous le system.
2- faire l'entree du stock(je prefere que l'entree soit comme dans une main warehouse et puis on les transfers sur les different outlets (ceci gere bien le stock pour la confusion dans le cas des grande quantites).
3- tous les outlets peut voir le stock pour tous les differents outlets (car si un client est dans outlet1 et veut une chemise par exemple le salesman peut l'aider a quel outlet peuvent trouver la chemise.

**Comment by pascalfares** [comment]
Rester dans le gestion de stock générique c'est mieux (pour vous aider utiliser des exemple si vous souhaiter)

**Comment by elieohanian** [comment]
ok merci docteur
