### ISSUE TITLE
Create Product Backlog

### ISSUE THREAD

**Issue by t-g-tannous** [projets2017cl/vc#50]
Dear,

I am trying to create the product Backlog related to the Workflow Product , but i wasn't able to do it under the VC folder , there is no button New 
![image](https://user-images.githubusercontent.com/22727196/27991815-a23c36da-648b-11e7-9b1a-442f3df6069b.png)

so i did it under the below  Link 

![image](https://user-images.githubusercontent.com/22727196/27991817-b31a4adc-648b-11e7-8015-c4eaa1b84248.png)

is it ok ? 

Thank you in advance

**Comment by pascalfares** [comment]
Vous n'avez pas les droit d'ecriture dans ce projet

Vous devez faire un fork dans un projet qui sera la copie de celui ci (un clone)

dans le fork vous m'ajouter en tant que mebre du projet avec les droits Read et Write

Je vous aiderais ensuite dans votre version du projet ...

**Comment by t-g-tannous** [comment]
Bonjour 

J'ai crée ce nouveau projet voici le lien 
https://github.com/projets2017cl/WorkflowProject
Aussi c'est ok pour le droit Read and Write . j'espere que c ok :) pour que je cloture ce ticket

Merci

**Comment by pascalfares** [comment]
En utilisant les issue, en créamt un label backlog par exemple vous pourrer filter tous les issue backlog

essayer ce filtre " is:issue is:open label:backlog "

**Comment by t-g-tannous** [comment]
Ok Merci
