### ISSUE TITLE
Question de java RMI

### ISSUE THREAD

**Issue by ansari007** [projets2017cl/vc#53]
Puis-je utiliser java rmi dans ce projet pour assurer un system reparti ou il n'est pas nécessaire de faire ca? @pascalfares

**Comment by pascalfares** [comment]
Web service plus facile probablement (les rmi necessite de configurer les "firewall") pas toujours facile

des service web peuvent être fait en embeded java  ou  node.js ou autre ...

**Comment by ansari007** [comment]
D'accord @pascalfares  merci :)
